version: '3.7'
services:
  handler:
    build:
      context: .
      target: build-env
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    entrypoint: ["/app/local-startup.sh"]
    command: ["--project", "/app/src/TicketType.Microservice.Template"]
    volumes:
    - ./src/TicketType.Microservice.Template:/app/src/TicketType.Microservice.Template
    - ./scripts/local/local-startup.sh:/app/local-startup.sh:ro
    - ./scripts/local/variant:/docker-entrypoint-initvariant.d:ro
    - ./scripts/local/wait-for-it.sh:/usr/local/bin/wait-for-it:ro
    environment:
      - AWS_ACCESS_KEY_ID=12345
      - AWS_SECRET_ACCESS_KEY=12345
      - AWS__ServiceURL=http://localstack:4576
      - SNS__ServiceURL=http://localstack:4576
      - SNS__Region=us-east-1
      - SQS__Region=us-east-1
      - SQS__QueueUrl=http://localstack:4576/000000000000/entity-queue
      - MessagePublisher__SnsTopics__Outgoing=arn:aws:sns:us-east-1:000000000000:tickets-topic
      - DOTNET_ENIVRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - GITHUB_USER
      - GITHUB_TOKEN
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack:0.11.2
    environment:
      - DEBUG=1
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - SERVICES=sqs,sns
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - 127.0.0.1:4567:4566
    volumes:
      - ./scripts/local/localstack:/docker-entrypoint-initaws.d:ro
networks:
  default:
    name: ticket-type-microservice-network