apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ required "AWS Secret K8S resource name is required" .Values.awsSecretResourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "TicketType.Microservice.Template.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  region: {{ required "envVars.awsRegion is required" .Values.envVars.awsRegion }}
  data:
    - key: {{ required "AWS Secret Name is required" .Values.awsSecretName }}
      name: ttmtsecrets.json