apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "TicketType.Microservice.Template.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "TicketType.Microservice.Template.labels" . | nindent 4 }}
  annotations:
    "eks.amazonaws.com/role-arn": "{{ required "serviceAccount.roleArn is required" .Values.serviceAccount.roleArn }}"
