deployable = "TicketType.Microservice.Template"
environment = "dev"
aws_policy_version           = "2012-10-17"
aws_default_region           = "us-east-1"
k8s_serviceaccount           = "ticket-type-microservice-dev"
team = "dev"
owner = "me"
revision = "0.0.0.1"
target_namespace = "local"
epsagon_app_name = "ticket-type-microservice-dev"
launch_darkly_key = ""
launch_darkly_user = "ticket-type-prototype-dev"
entity_api_incoming_queue_url = "http://localstack:4566/queue/entity-queue"
ticketing_api_outgoing_topic_name = "tickets-topic"
entity_api_incoming_topic_name = "entity-topic"
ticketing_api_outgoing_topic_arn = "arn:aws:sns:us-east-1:000000000000:tickets-topic"
project_name = "local-proj"

